# The line below states we will base our new image on the Latest Official Ubuntu 
FROM ubuntu:latest

#
# Identify the maintainer of an image
LABEL maintainer="dharanisri201@gmail.com"

#
# Update the image to the latest packages
RUN apt-get update && apt-get upgrade -y

#
# Expose port 80
EXPOSE 80
